[env:m5stack_cardputer]
platform = https://github.com/pioarduino/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = espidf
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.prsam_type = qspi
board_upload.flash_size = 8MB

build_flags = 
    ${env.build_flags}
    -D BOARD_PROFILE_PATH=\"boards/m5stack_cardputer/m5stack_cardputer.toml\"
    -D CONFIG_SPIRAM_MODE_QUAD=1
    -D BOARD_HAS_PSRAM=1
    -D CONFIG_ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_ARDUINO_USB_MODE=1
